# image: registry.gitlab.com/chromaway/core-tools/chromia-images/node21-java21:1.2.0@sha256:c04590bf5702e3e3071ac3bae28ad4e1129ac7239e1bfd655451f718807ca1fd

image: registry.gitlab.com/chromaway/ft4-lib

stages:
  - build
  - test
  - deploy

variables:
  MAX_TIME: "15"

default:
  tags:
    - gitlab-org-docker

# before_script:
#   - apt-get update
#   - apt-get install ca-certificates curl
#   - install -m 0755 -d /etc/apt/keyrings
#   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
#   - chmod a+r /etc/apt/keyrings/docker.asc

#     # Add the repository to Apt sources:
#   - echo \
#       "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
#       $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#        tee /etc/apt/sources.list.d/docker.list > /dev/null
#   - apt-get update
#   - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

cache:
  paths:
    - node_modules/

services:
  - name: postgres
    alias: postgres
    variables:
      POSTGRES_DB: "postchain"
      POSTGRES_USER: "postchain"
      POSTGRES_PASSWORD: "postchain"
      POSTGRES_INITDB_ARGS: "--lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8"

unit_integration_tests:
  stage: test
  script:
    - ./scripts/install-chr-and-pmc.sh
    - echo ${BUILD_BOT_EMAIL_ADDRESS}
    - echo ${BUILD_BOT_API_KEY}
    - chr install
    - chr build
    # - chr test --use-db --test-report --test-report-dir=test-reports/rell || (curl --no-progress-meter -X POST https://chromadev.zulipchat.com/api/v1/messages -u ${BUILD_BOT_EMAIL_ADDRESS}:${BUILD_BOT_API_KEY} --data-urlencode type=stream --data-urlencode 'to="Protocols - FT4 builds"' --data-urlencode 'topic=Build failed' --data-urlencode "content=Rell tests failed on [Bitbucket](https://bitbucket.org/chromawallet/ft3-lib/pipelines/results/${BITBUCKET_BUILD_NUMBER})." ; exit 1)
    - chr test
    - npm ci
    - npm run compile
    - npm run generate:docs
    - export JEST_JUNIT_OUTPUT_NAME=unit.xml
    - npx jest -maxWorkers=1 --testPathPattern=unit/ --ci --reporters=default --reporters=jest-junit || (curl --no-progress-meter -X POST https://chromadev.zulipchat.com/api/v1/messages -u ${BUILD_BOT_EMAIL_ADDRESS}:${BUILD_BOT_API_KEY} --data-urlencode type=stream --data-urlencode 'to="Protocols - FT4 builds"' --data-urlencode 'topic=Build failed' --data-urlencode "content=TS unit tests failed on [Bitbucket](https://bitbucket.org/chromawallet/ft3-lib/pipelines/results/${BITBUCKET_BUILD_NUMBER})." ; exit 1)
    - export TESTCONTAINERS_RYUK_DISABLED=true
    - export JEST_JUNIT_OUTPUT_NAME=integration.xml
    - npx jest --config=jest.config.integration.js -maxWorkers=1 --testPathPattern=integration/ --ci --reporters=default --reporters=jest-junit || (curl --no-progress-meter -X POST https://chromadev.zulipchat.com/api/v1/messages -u ${BUILD_BOT_EMAIL_ADDRESS}:${BUILD_BOT_API_KEY} --data-urlencode type=stream --data-urlencode 'to="Protocols - FT4 builds"' --data-urlencode 'topic=Build failed' --data-urlencode "content=TS integration tests failed on [Bitbucket](https://bitbucket.org/chromawallet/ft3-lib/pipelines/results/${BITBUCKET_BUILD_NUMBER})." ; exit 1)
  artifacts:
    paths:
      - logs/**

# e2e_tests:
#   stage: test
#   image: cypress/browsers:node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1
#   script:
#     - export DISPLAY=:0.0
#     - Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
#     - fluxbox &
#     - npm ci
#     - npm run test:e2e || (curl --no-progress-meter -X POST https://chromadev.zulipchat.com/api/v1/messages -u ${BUILD_BOT_EMAIL_ADDRESS}:${BUILD_BOT_API_KEY} --data-urlencode type=stream --data-urlencode 'to="Protocols - FT4 builds"' --data-urlencode 'topic=Build failed' --data-urlencode "content=E2E tests failed on [Bitbucket](https://bitbucket.org/chromawallet/ft3-lib/pipelines/results/${BITBUCKET_BUILD_NUMBER})." ; exit 1)
#   artifacts:
#     paths:
#       - logs/**
#       - cypress/screenshots/**
#       - cypress/videos/**

multichain_tests:
  services:
    - docker
  stage: test
  script:
    - ./scripts/install-chr-and-pmc.sh
    - npm ci
    - systemctl start docker
    - chmod +x ./scripts/multichain-jesttest.sh; ./scripts/multichain-jesttest.sh

update_docs:
  stage: deploy
  script:
    - ./scripts/update-docs.sh

# deploy_latest:
#   stage: deploy
#   script:
#     - ./scripts/install-chr-and-pmc.sh
#     - chr install
#     - mkdir .chromia
#     - printf $DEPLOYMENT_KEYS > .chromia/config
#     - npm run deploy:latest
#     - rm .chromia/config

# deploy_stable:
#   stage: deploy
#   script:
#     - ./scripts/install-chr-and-pmc.sh
#     - chr install
#     - mkdir .chromia
#     - printf $DEPLOYMENT_KEYS > .chromia/config
#     - npm run deploy:stable
#     - rm .chromia/config

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - "*"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - "*"
      when: always
    - if: $CI_COMMIT_BRANCH == "ft4"
      changes:
        - "*"
      when: always
    # - if: $CI_COMMIT_BRANCH == "development"
    #   when: manual
    # - if: $CI_COMMIT_BRANCH == "ft4"
    #   when: manual
