image: node:18

options:
  max-time: 15

pipelines:
  pull-requests:
    '**':
      # - step:
      #     size: 2x
      #     name: Test
      #     caches:
      #       - node
      #     script:
      #       - apt update
      #       - curl -fsSL https://apt.chromia.com/chromia.gpg >/usr/share/keyrings/chromia.gpg
      #       - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chromia.gpg] https://apt.chromia.com stable main" >/etc/apt/sources.list.d/chromia.list
      #       - apt update
      #       - apt install -y netcat-openbsd chr default-jre
      #       - chr install -s configs/rell-test.yml
      #       - chr test -s configs/rell-test.yml --use-db --test-report --test-report-dir=test-reports/rell
      #       - npm ci
      #       - export JEST_JUNIT_OUTPUT_NAME=unit.xml
      #       - npx jest -maxWorkers=1 --testPathPattern=unit/ --ci --reporters=default --reporters=jest-junit
      #       - export TESTCONTAINERS_RYUK_DISABLED=true
      #       - export JEST_JUNIT_OUTPUT_NAME=integration.xml
      #       - npx jest --config=jest.config.integration.js -maxWorkers=1 --testPathPattern=integration/ --ci --reporters=default --reporters=jest-junit
      #     services:
      #       - postgres
      #       - docker
      - step:
          max-time: 15
          name: E2E Tests
          # image: cypress/browsers:node18.12.0-chrome107
          # image: cypress/browsers:node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
          image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
          size: 2x
          caches:
            - node
            - cypress
          script:
            # Clean up duplicate entries in the sources list for Microsoft Edge
            - rm -vf /etc/apt/sources.list.d/microsoft-edge-stable.list
            - rm -vf /etc/apt/sources.list.d/microsoft-edge.list
            - apt-get update
            - apt-get install -y curl lsof fluxbox xvfb netcat-openbsd openjdk-11-jre-headless
            - curl -fsSL https://apt.chromia.com/chromia.gpg >/usr/share/keyrings/chromia.gpg
            - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chromia.gpg] https://apt.chromia.com stable main" >/etc/apt/sources.list.d/chromia.list
            - apt update
            - apt install -y chr
            - export DISPLAY=:0.0
            - Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
            - fluxbox &
            - npm ci
            - npm run test:e2e
          artifacts:
            - cypress/screenshots/**
            - cypress/videos/**
          services:
            - docker
  branches:
    ft4:
      - step:
          name: deploy:latest
          script:
            - apt update
            - curl -fsSL https://apt.chromia.com/chromia.gpg >/usr/share/keyrings/chromia.gpg
            - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chromia.gpg] https://apt.chromia.com stable main" >/etc/apt/sources.list.d/chromia.list
            - apt update
            - apt install default-jre -y
            - apt install chr
            - chr install -s configs/jest-test.yml
            - mkdir .chromia
            - printf $DEPLOYMENT_KEYS > .chromia/config
            - npm run deploy:latest
            - rm .chromia/config
  custom:
    deploy-to-stable:
      - step:
          name: deploy:stable
          script:
            - apt update
            - curl -fsSL https://apt.chromia.com/chromia.gpg >/usr/share/keyrings/chromia.gpg
            - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chromia.gpg] https://apt.chromia.com stable main" >/etc/apt/sources.list.d/chromia.list
            - apt update
            - apt install default-jre -y
            - apt install chr
            - chr install -s configs/jest-test.yml
            - mkdir .chromia
            - printf $DEPLOYMENT_KEYS > .chromia/config
            - npm run deploy:stable
            - rm .chromia/config
    deploy-to-latest:
      - step:
          name: deploy:latest
          script:
            - apt update
            - curl -fsSL https://apt.chromia.com/chromia.gpg >/usr/share/keyrings/chromia.gpg
            - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chromia.gpg] https://apt.chromia.com stable main" >/etc/apt/sources.list.d/chromia.list
            - apt update
            - apt install default-jre -y
            - apt install chr
            - chr install -s configs/jest-test.yml
            - mkdir .chromia
            - printf $DEPLOYMENT_KEYS > .chromia/config
            - npm run deploy:latest
            - rm .chromia/config
    ft4-201-e2e-pipeline:
      - step:
          name: E2E Tests
          image: cypress/browsers:node18.16.0-chrome101-ff99
          size: 2x
          caches:
            - node
            - cypress
          script:
            - npm ci
            - npm run test:e2e:headless
          artifacts:
            - cypress/screenshots/**
            - cypress/videos/**
    development:
      - step:
          name: E2E Tests
          image: cypress/browsers:node18.16.0-chrome101-ff99
          size: 2x
          caches:
            - node
            - cypress
          script:
            - npm ci
            - npm run test:e2e:headless
          artifacts:
            - cypress/screenshots/**
            - cypress/videos/**
definitions: 
  caches:
    cypress: $BITBUCKET_CLONE_DIR/.cache/Cypress
  services: 
    postgres: 
      image: postgres 
      variables: 
        POSTGRES_DB: 'postchain' 
        POSTGRES_USER: 'postchain'
        POSTGRES_PASSWORD: 'postchain'
        POSTGRES_INITDB_ARGS: '--lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8'
