version: "3.3"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
      POSTGRES_PASSWORD: postchain

  ft3-test:
    image: registry.gitlab.com/chromaway/postchain-distribution/chromaway/postchain-test-dapp:3.5.0
    container_name: ft3-lib
    command:
      - run-node-auto
    ports:
      - "7740:7740"
    depends_on:
      - postgres
    volumes:
      - ./postchain/config/nodes/test:/opt/chromaway/rell/config
      - ./rell:/opt/chromaway/rell
    environment:
      POSTCHAIN_DB_URL: jdbc:postgresql://postgres/postchain

