version: "3.3"

services:
  ft3-lib-jest-postgres:
    image: postgres:14.1-alpine
    container_name: ft3-lib-jest-postgres
    restart: always
    environment:
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
      POSTGRES_PASSWORD: postchain

  ft3-lib-jest-postchain:
    image: registry.gitlab.com/chromaway/postchain-distribution/chromaway/postchain-test-dapp:3.5.0
    container_name: ft3-lib-jest-postchain
    command:
      - run-node-auto
    ports:
      - "7741:7740"
    depends_on:
      - ft3-lib-jest-postgres
    volumes:
      - ../rell:/opt/chromaway/rell
    environment:
      POSTCHAIN_DB_URL: jdbc:postgresql://ft3-lib-jest-postgres/postchain

