version: 0.0
os: linux

files:
  - source: ./
    destination: /opt/ft3

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: root
