blockchains:
  ft4_demo: #Name of the blockchain
    module: main #Entrypoint to the project
    moduleArgs:
      lib.ft4.core.admin:
        admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

      lib.ft4.core.accounts.strategies.transfer: # placeholder
        rules: 
          timeout_days: 10

compile:
  source: ../rell/src
  target: ../rell/out
  rellVersion: 0.14.12

libs:
  iccf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/lib/iccf
    tagOrBranch: 1.87.0
    rid: x"9C359787B75927733034EA1CEE74EEC8829D2907E4FC94790B5E9ABE4396575D"

  iccf_test:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/lib/test/iccf
    tagOrBranch: 1.87.0
    rid: x"873D71557531E35E453587FA71C2D3CCB674F0EB49D18B30FA838C52C1155EB3"
