blockchains:
  ft_deploy: #Name of the blockchain
    module: main #Entrypoint to the project
    moduleArgs:
      lib.ft3.core:
        rate_limit_active: 1
        rate_limit_max_points: 10
        rate_limit_recovery_time: 5000
        rate_limit_points_at_account_creation: 1

compile:
  source: ../rell/src
  target: ../rell/out

deployments:
  devnet1: #Deployment Target name
    url: https://node0.devnet1.chromia.dev:7740
    brid: x"43B6185404EA6CB51FC179748B78B2295A1B20F267826807F905B691FC4BD1D0"
    container: ft
    chains:
      ft_deploy: x"CB5F9543C949AAFD8D967C02306465BED83263C9A460DC79C425C0D9DB35ACE9"