blockchains:
  ft4_jest_test:  # Name of the blockchain
    module: tests.client_test_app_module  # Entrypoint to the project
    moduleArgs:
      lib.ft4.core.accounts:
        rate_limit:
          max_points: 10
          recovery_time: 5000
          points_at_account_creation: 2

      lib.ft4.core.admin:
        admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

      lib.ft4.core.accounts.strategies.transfer:
        rules: 
          - sender_blockchain: "$"
            sender: "*"
            recipient: "*"
            asset:
              - name: transfer_strategy_asset
                min_amount: 5L
              - name: transfer_fee_strategy_asset
                min_amount: 5L
              - name: transfer_subscription_strategy_asset
                min_amount: 5L
            timeout_days: 1
            strategy:
              - "open"
              - "fee"
              - "subscription"
          - sender_blockchain: "$"
            sender: "*"
            recipient: "*"
            asset:
              - name: timeout_asset
                min_amount: 5L
            timeout_days: 0
            strategy:
              - "open"
              - "fee"
              - "subscription"

      lib.ft4.core.accounts.strategies.transfer.fee:
        asset:
          name: transfer_fee_strategy_asset
          amount: 2L

      lib.ft4.core.accounts.strategies.transfer.subscription:
        asset:
          name: transfer_subscription_strategy_asset
          amount: 2L
        subscription_period_days: 30

      lib.ft4.core.accounts.strategies.import_strategy:  
        trusted_chains:
          - x"1399802DE4738134DAF9962B3BFB02EB2FF8EC9BCBCA31A0E586C174C92263C7"
          - x"75E018CDBB597CC212533CBD90B4433195AE0421FAD0E7CF8BF6C7F4829C99B9"
          - x"93866CB5A7769EFC7EE052B8EB06CEE44CC23957377B35C256FA7384ACE0FBA3"
        import_account_timeout: 30
        allow_modified_main_auth_descriptors: false  

# database:
#   password: postchain
#   username: postchain
#   database: postchain
#   host: postgres:5432
#   logSqlErrors: true
#   schema: multichain_tests
#   driver: org.postgresql.Driver        

libs:
  iccf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/lib/iccf
    tagOrBranch: 1.87.0
    rid: x"9C359787B75927733034EA1CEE74EEC8829D2907E4FC94790B5E9ABE4396575D"

  iccf_test:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/lib/test/iccf
    tagOrBranch: 1.87.0
    rid: x"873D71557531E35E453587FA71C2D3CCB674F0EB49D18B30FA838C52C1155EB3"

compile:
  source: ../rell/src
  target: ../rell/out
  rellVersion: 0.14.5
