blockchains:
  ft4_jest_test:  # Name of the blockchain
    module: tests.client_test_app_module  # Entrypoint to the project
    moduleArgs:
      lib.ft4.accounts:
        rate_limit:
          max_points: 10
          recovery_time: 5000
          points_at_account_creation: 2

      lib.ft4.admin:
        admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

      lib.ft4.accounts.strategies.transfer:
        rules: 
          - sender_blockchain:
            - "$"
            sender: "*"
            recipient: "*"
            asset:
              - id: x"b31ba66a11a28930d948c8f959cc306184096d1ee858542e765a139b3c79b1aa"
                min_amount: 5L
            timeout_days: 1
            strategy:
              - "open"
              - "fee"

libs:
  iccf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/iccf
    tagOrBranch: 1.9.1
    rid: x"593D6EBA650BAC473E105C047B2C43A099164870304B3E5E324F714FF2F3F82F"

compile:
  source: ../rell/src
  target: ../rell/out
  rellVersion: 0.13.5
