blockchains:
  ft3_jest_test: #Name of the blockchain
    module: main #Entrypoint to the project
    moduleArgs:
      lib.ft3.core:
        rate_limit_active: 1
        rate_limit_max_points: 10
        rate_limit_recovery_time: 5000
        rate_limit_points_at_account_creation: 1

      lib.ft3.operations.dev_op:
        admin_pub_key: 02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD        

compile:
  source: ../rell/src
  target: ../rell/out
