blockchains:
  # Name of the blockchain
  ft4_multichain_test:
    # Entrypoint to the dummy application
    module: multichain.app_module{chain_number}
    config:
      blockstrategy:
        blockdelay: 2000
        maxblocktime: 2000
        maxblocktransactions: 500

compile:
  source: ../rell/dep/
  target: ../rell/out
