blockchains:
  ft4_rell_test:  # Name of the blockchain
    module: tests.assets.app_module  # Entrypoint to the project
    test:  # Not default
      modules:  # List of the test modules in your project
        - tests.accounts
        - tests.assets        
        - tests.auth
        - tests.crosschain
        - tests.default_prioritization
        - tests.utils
      moduleArgs:
        lib.ft4:
          query_max_page_size: 99

        lib.ft4.accounts:
          rate_limit:
            max_points: 5
            # Use default values for the other rate limit parameters
          max_auth_descriptor_rules: 4

        lib.ft4.admin:
          admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

        tests.assets.utils:
          admin_priv_key: x"00CED79962D1150BF844CACB76310D4746C4426558A7FD9C827B30203DACC4CE"

  ft4_rell_auth:  # Runs separate test chain to test auth extensions
    module: tests.assets.app_module_2  # Entrypoint to the project
    test:
      modules:
        - tests.auth_extensions
      moduleArgs:
        # Use default values for all rate limit parameters

        lib.ft4.admin:
          admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

        tests.assets.utils:
          admin_priv_key: x"00CED79962D1150BF844CACB76310D4746C4426558A7FD9C827B30203DACC4CE"

  ft4_rell_create_account_strategies:  # Runs separate test chain to test create account strategies
    module: tests.assets.app_module  # Entrypoint to the project
    test:
      modules:
        - tests.create_account_strategies
      moduleArgs:
        # Use default values for all rate limit parameters

        lib.ft4.admin:
          admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

        tests.assets.utils:
          admin_priv_key: x"00CED79962D1150BF844CACB76310D4746C4426558A7FD9C827B30203DACC4CE"

        lib.ft4.accounts.strategies.transfer:
          rules: 
            - sender_blockchain: 
              - x"08B02E0E14B634031FDF2ED3FD78E7410A5849CD28"
              - "$"
              sender: X
              recipient: X
              timeout_days: 10
              strategy: "open"

            - sender: "*"
              recipient: x"7b1dda0d03d062460c745b459779e1dee9845a5eec6341a81f91c081c5cc89c5" # Alice
              asset:
                - id: x"abcdef"
                  min_amount: 100000L
              timeout_days: 60
              strategy:
               - "fee"
               - "stake"

            - sender_blockchain:
              - x"6403ccac0c67f7cb6af78e5e15b3aaebb2b42370f0d12e099ed01fa5a068f9fb"
              - "$"
              sender: "*"
              recipient:
                - x"e7240d97ba8a49f146f3464f8193491f68bb48f55d85307fd1c5ea24e233bbd8" # Bob
              asset:
                - id: x"b31ba66a11a28930d948c8f959cc306184096d1ee858542e765a139b3c79b1aa"
                  min_amount: 5L
                - id: x"0bdb46231fb6b6fde8efd06dbab99dff23de1ec3dcab2cc43d3acc7fe62da7ac"
                  min_amount: 3L
                - id: x"ad60efda802fec15e22a8c4691d1eb13e144dee4984772c05ab9163cf2cf2996"
                  min_amount: 5L
                - id: x"39b34b11bf6c1c301327d5824f977c9360895446a529bb980ebefd2183ca4831"
                  min_amount: 5L
                - id: x"cf45a2cf3033543c2664886c7d39f9f31087bd5949120fe2e69affc0f926a71f"
                  min_amount: 7L
              timeout_days: 60
              strategy:
                - "open"
                - "fee"

            - sender_blockchain:
              - "$"
              sender: "*"
              recipient: x"a088742ac287d9a2cd2efdbbdb75c4f7538cb390ebbb1e375669b170e5915bbe" # Charlie
              timeout_days: 60
              strategy:
                - "open"

        lib.ft4.accounts.strategies.transfer.fee:
          asset:
            - id: x"b31ba66a11a28930d948c8f959cc306184096d1ee858542e765a139b3c79b1aa"
              amount: 2L
            - id: x"0bdb46231fb6b6fde8efd06dbab99dff23de1ec3dcab2cc43d3acc7fe62da7ac"
              amount: 1L

libs:
  iccf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/iccf
    tagOrBranch: 1.9.1
    rid: x"593D6EBA650BAC473E105C047B2C43A099164870304B3E5E324F714FF2F3F82F"

compile:
  source: ../rell/src
  rellVersion: 0.13.5
