blockchains:
  ft4_rell_test:  # Name of the blockchain
    module: tests.assets.app_module  # Entrypoint to the project
    test:  # Not default
      modules:  # List of the test modules in your project
        - tests.accounts
        - tests.assets        
        - tests.auth
        - tests.crosschain
        - tests.default_prioritization
        - tests.utils
      moduleArgs:
        lib.ft4:
          query_max_page_size: 99

        lib.ft4.accounts:
          rate_limit:
            max_points: 5
            # Use default values for the other rate limit parameters
          max_auth_descriptor_rules: 4

        lib.ft4.admin:
          admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

        tests.assets.utils:
          admin_priv_key: x"00CED79962D1150BF844CACB76310D4746C4426558A7FD9C827B30203DACC4CE"

  ft4_rell_auth:  # Runs separate test chain to test auth extensions
    module: tests.assets.app_module_2  # Entrypoint to the project
    test:
      modules:
        - tests.auth_extensions
      moduleArgs:
        # Use default values for all rate limit parameters

        lib.ft4.admin:
          admin_pubkey: x"02C4049F9550DCFF6003347BB3944DF2AA2D6EF5202C22834284B085C56DE8C6DD"

        tests.assets.utils:
          admin_priv_key: x"00CED79962D1150BF844CACB76310D4746C4426558A7FD9C827B30203DACC4CE"

libs:
  iccf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/iccf
    tagOrBranch: 1.9.1
    rid: x"593D6EBA650BAC473E105C047B2C43A099164870304B3E5E324F714FF2F3F82F"

compile:
  source: ../rell/src
  rellVersion: 0.13.5
